import {
  Layers,
  Scissors,
  Minimize2,
  FileText,
  FileUp,
  FileDown,
  Image as ImageIcon,
  PenTool,
  Sparkles,
  ScanLine,
  Unlock,
  Lock,
  Table,
  Presentation,
  FileSpreadsheet,
  Stamp,
  RotateCw,
  Trash2,
  Code2,
  Type,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  Layers,
  Scissors,
  Minimize2,
  FileText,
  FileUp,
  FileDown,
  Image: ImageIcon,
  PenTool,
  Sparkles,
  ScanLine,
  Unlock,
  Lock,
  Table,
  Presentation,
  FileSpreadsheet,
  Stamp,
  RotateCw,
  Trash2,
  Code2,
  Type,
};

export const TOOL_KEYS = [
  { slug: "merge-pdf", icon: "Layers", nameKey: "tools.mergePdf.name", descKey: "tools.mergePdf.description", category: "organize" },
  { slug: "split-pdf", icon: "Scissors", nameKey: "tools.splitPdf.name", descKey: "tools.splitPdf.description", category: "organize" },
  { slug: "rotate-pdf", icon: "RotateCw", nameKey: "tools.rotatePdf.name", descKey: "tools.rotatePdf.description", category: "organize" },
  { slug: "delete-pdf", icon: "Trash2", nameKey: "tools.deletePdf.name", descKey: "tools.deletePdf.description", category: "organize" },
  { slug: "extract-pdf", icon: "FileDown", nameKey: "tools.extractPdf.name", descKey: "tools.extractPdf.description", category: "organize" },
  { slug: "compress-pdf", icon: "Minimize2", nameKey: "tools.compressPdf.name", descKey: "tools.compressPdf.description", category: "optimize" },
  { slug: "pdf-to-word", icon: "FileText", nameKey: "tools.pdfToWord.name", descKey: "tools.pdfToWord.description", category: "convert-from" },
  { slug: "pdf-to-excel", icon: "Table", nameKey: "tools.pdfToExcel.name", descKey: "tools.pdfToExcel.description", category: "convert-from" },
  { slug: "pdf-to-ppt", icon: "Presentation", nameKey: "tools.pdfToPpt.name", descKey: "tools.pdfToPpt.description", category: "convert-from" },
  { slug: "word-to-pdf", icon: "FileUp", nameKey: "tools.wordToPdf.name", descKey: "tools.wordToPdf.description", category: "convert-to" },
  { slug: "excel-to-pdf", icon: "FileSpreadsheet", nameKey: "tools.excelToPdf.name", descKey: "tools.excelToPdf.description", category: "convert-to" },
  { slug: "ppt-to-pdf", icon: "Presentation", nameKey: "tools.pptToPdf.name", descKey: "tools.pptToPdf.description", category: "convert-to" },
  { slug: "jpg-to-pdf", icon: "Image", nameKey: "tools.jpgToPdf.name", descKey: "tools.jpgToPdf.description", category: "convert-to" },
  { slug: "html-to-pdf", icon: "Code2", nameKey: "tools.htmlToPdf.name", descKey: "tools.htmlToPdf.description", category: "convert-to" },
  { slug: "txt-to-pdf", icon: "Type", nameKey: "tools.txtToPdf.name", descKey: "tools.txtToPdf.description", category: "convert-to" },
  { slug: "sign-pdf", icon: "PenTool", nameKey: "tools.signPdf.name", descKey: "tools.signPdf.description", category: "edit", isPro: true },
  { slug: "add-watermark", icon: "Stamp", nameKey: "tools.addWatermark.name", descKey: "tools.addWatermark.description", category: "edit" },
  { slug: "ai-pdf-summarizer", icon: "Sparkles", nameKey: "tools.aiPdfSummarizer.name", descKey: "tools.aiPdfSummarizer.description", category: "ai", isPro: true },
  { slug: "pdf-scanner", icon: "ScanLine", nameKey: "tools.pdfScanner.name", descKey: "tools.pdfScanner.description", category: "scan" },
  { slug: "unlock-pdf", icon: "Unlock", nameKey: "tools.unlockPdf.name", descKey: "tools.unlockPdf.description", category: "security" },
  { slug: "protect-pdf", icon: "Lock", nameKey: "tools.protectPdf.name", descKey: "tools.protectPdf.description", category: "security" },
] as const;

export const FAQ_KEYS = ["faq1", "faq2", "faq3", "faq4", "faq5", "faq6", "faq7"] as const;

export const FREE_FEATURES = [
  "5 tool uses per day",
  "No file size limit",
  "Basic PDF tools",
  "Standard processing speed",
  "Files deleted after 2 hours",
];

export const PRO_FEATURES = [
  "100 tool uses per day",
  "No file size limit",
  "All PDF tools including Sign & AI",
  "AI PDF Summarizer",
  "Priority processing",
  "No ads",
  "Batch processing",
];

export const TOOL_CATEGORIES = [
  { id: "organize", labelKey: "landing.toolsCategoryOrganize" },
  { id: "optimize", labelKey: "landing.toolsCategoryOptimize" },
  { id: "convert-from", labelKey: "landing.toolsCategoryConvertFrom" },
  { id: "convert-to", labelKey: "landing.toolsCategoryConvertTo" },
  { id: "edit", labelKey: "landing.toolsCategoryEdit" },
  { id: "security", labelKey: "landing.toolsCategorySecurity" },
  { id: "ai", labelKey: "landing.toolsCategoryAi" },
  { id: "scan", labelKey: "landing.toolsCategoryScan" },
] as const;

export const CATEGORY_FALLBACK_LABELS: Record<string, string> = {
  organize: "Organize PDF",
  optimize: "Optimize PDF",
  "convert-from": "Convert from PDF",
  "convert-to": "Convert to PDF",
  edit: "Edit & Sign",
  security: "Security",
  ai: "AI Tools",
  scan: "Scan",
};

/** iLovePDF-style colored icon tiles per tool */
export const TOOL_ACCENT: Record<string, string> = {
  "merge-pdf": "bg-[#E74C3C]",
  "split-pdf": "bg-[#E67E22]",
  "rotate-pdf": "bg-[#9B59B6]",
  "delete-pdf": "bg-[#E74C3C]",
  "extract-pdf": "bg-[#3498DB]",
  "compress-pdf": "bg-[#27AE60]",
  "pdf-to-word": "bg-[#2980B9]",
  "pdf-to-excel": "bg-[#16A085]",
  "pdf-to-ppt": "bg-[#D35400]",
  "word-to-pdf": "bg-[#3498DB]",
  "excel-to-pdf": "bg-[#2ECC71]",
  "ppt-to-pdf": "bg-[#C0392B]",
  "jpg-to-pdf": "bg-[#9B59B6]",
  "html-to-pdf": "bg-[#E65100]",
  "txt-to-pdf": "bg-[#5C6BC0]",
  "sign-pdf": "bg-[#34495E]",
  "add-watermark": "bg-[#7F8C8D]",
  "ai-pdf-summarizer": "bg-[#6C5CE7]",
  "pdf-scanner": "bg-[#00B894]",
  "unlock-pdf": "bg-[#F39C12]",
  "protect-pdf": "bg-[#E84393]",
};
