import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import puppeteer from "puppeteer";
import { formatSummaryParagraphs } from "@/lib/ai/sanitize-summary";

export type SummaryExportFormat = "txt" | "docx" | "pdf";

export interface SummaryExportInput {
  documentTitle?: string;
  topics?: string[];
  shortSummary: string;
  detailedSummary: string;
  keyPoints: string[];
  actionItems: string[];
  importantDates: string[];
  sourceFileName?: string;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "pdf-summary";
}

export function getSummaryExportFilename(
  summary: SummaryExportInput,
  format: SummaryExportFormat
): string {
  const base = slugify(summary.documentTitle || "document-summary");
  const ext = format === "docx" ? "docx" : format === "pdf" ? "pdf" : "txt";
  return `${base}-summary.${ext}`;
}

function buildPlainText(summary: SummaryExportInput): string {
  const title = summary.documentTitle || "Document Summary";
  const detailed = formatSummaryParagraphs(summary.detailedSummary);

  return [
    title,
    "=".repeat(Math.min(title.length, 60)),
    summary.sourceFileName ? `Source: ${summary.sourceFileName}` : "",
    summary.topics?.length ? `Topics: ${summary.topics.join(", ")}` : "",
    "",
    "EXECUTIVE SUMMARY",
    summary.shortSummary,
    "",
    "DETAILED ANALYSIS",
    ...detailed,
    "",
    "KEY INSIGHTS",
    ...summary.keyPoints.map((point, index) => `${index + 1}. ${point}`),
    "",
    "RECOMMENDED ACTIONS",
    ...summary.actionItems.map((item, index) => `${index + 1}. ${item}`),
    ...(summary.importantDates.length
      ? [
          "",
          "DATES & METRICS",
          ...summary.importantDates.map((item, index) => `${index + 1}. ${item}`),
        ]
      : []),
    "",
    "Generated by Only4PDF - only4pdf.com",
  ]
    .filter(Boolean)
    .join("\n");
}

function heading(text: string) {
  return new Paragraph({
    text,
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 280, after: 120 },
  });
}

function bodyParagraph(text: string) {
  return new Paragraph({
    children: [new TextRun({ text, size: 22 })],
    spacing: { after: 160 },
  });
}

function bulletParagraph(text: string) {
  return new Paragraph({
    text,
    bullet: { level: 0 },
    spacing: { after: 100 },
  });
}

export async function exportSummaryAsDocx(summary: SummaryExportInput): Promise<Buffer> {
  const title = summary.documentTitle || "Executive Summary Report";
  const detailed = formatSummaryParagraphs(summary.detailedSummary);

  const children: Paragraph[] = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.TITLE,
      spacing: { after: 120 },
    }),
  ];

  if (summary.sourceFileName) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Source file: ${summary.sourceFileName}`,
            italics: true,
            color: "666666",
            size: 20,
          }),
        ],
        spacing: { after: 200 },
      })
    );
  }

  children.push(heading("Executive Summary"));
  children.push(bodyParagraph(summary.shortSummary));

  children.push(heading("Detailed Analysis"));
  for (const paragraph of detailed) {
    children.push(bodyParagraph(paragraph));
  }

  if (summary.keyPoints.length > 0) {
    children.push(heading("Key Insights"));
    for (const point of summary.keyPoints) {
      children.push(bulletParagraph(point));
    }
  }

  if (summary.actionItems.length > 0) {
    children.push(heading("Recommended Actions"));
    for (const item of summary.actionItems) {
      children.push(bulletParagraph(item));
    }
  }

  if (summary.importantDates.length > 0) {
    children.push(heading("Dates & Metrics"));
    for (const item of summary.importantDates) {
      children.push(bulletParagraph(item));
    }
  }

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by Only4PDF",
          italics: true,
          color: "666666",
          size: 18,
        }),
      ],
      spacing: { before: 280 },
    })
  );

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildSummaryHtml(summary: SummaryExportInput): string {
  const title = escapeHtml(summary.documentTitle || "Executive Summary Report");
  const detailed = formatSummaryParagraphs(summary.detailedSummary).map(escapeHtml);
  const topics = (summary.topics || []).map(escapeHtml);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <style>
    @page { size: A4; margin: 18mm 16mm; }
    body {
      font-family: Calibri, "Segoe UI", Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.55;
      color: #1f2937;
      margin: 0;
    }
    .hero {
      background: linear-gradient(135deg, #6d28d9, #4f46e5);
      color: white;
      padding: 24px 22px;
      border-radius: 14px;
      margin-bottom: 24px;
    }
    .hero h1 {
      margin: 0 0 8px;
      font-size: 22pt;
      line-height: 1.2;
    }
    .hero p { margin: 0; opacity: 0.92; font-size: 10pt; }
    .tags { margin-top: 14px; }
    .tag {
      display: inline-block;
      background: rgba(255,255,255,0.16);
      border-radius: 999px;
      padding: 4px 10px;
      margin: 0 6px 6px 0;
      font-size: 9pt;
    }
    h2 {
      color: #5b21b6;
      font-size: 14pt;
      margin: 24px 0 10px;
      page-break-after: avoid;
    }
    p { margin: 0 0 10px; }
    ul { margin: 0 0 12px 0; padding-left: 18px; }
    li { margin-bottom: 8px; }
    .card {
      background: #f9fafb;
      border: 1px solid #e5e7eb;
      border-radius: 10px;
      padding: 12px 14px;
      margin-bottom: 10px;
    }
    .footer {
      margin-top: 28px;
      font-size: 9pt;
      color: #6b7280;
      border-top: 1px solid #e5e7eb;
      padding-top: 10px;
    }
  </style>
</head>
<body>
  <div class="hero">
    <h1>${title}</h1>
    ${summary.sourceFileName ? `<p>Source: ${escapeHtml(summary.sourceFileName)}</p>` : ""}
    ${
      topics.length
        ? `<div class="tags">${topics.map((topic) => `<span class="tag">${topic}</span>`).join("")}</div>`
        : ""
    }
  </div>

  <h2>Executive Summary</h2>
  <p>${escapeHtml(summary.shortSummary)}</p>

  <h2>Detailed Analysis</h2>
  ${detailed.map((paragraph) => `<p>${paragraph}</p>`).join("")}

  ${
    summary.keyPoints.length
      ? `<h2>Key Insights</h2><ul>${summary.keyPoints
          .map((point) => `<li>${escapeHtml(point)}</li>`)
          .join("")}</ul>`
      : ""
  }

  ${
    summary.actionItems.length
      ? `<h2>Recommended Actions</h2><ul>${summary.actionItems
          .map((item) => `<li>${escapeHtml(item)}</li>`)
          .join("")}</ul>`
      : ""
  }

  ${
    summary.importantDates.length
      ? `<h2>Dates &amp; Metrics</h2>${summary.importantDates
          .map((item) => `<div class="card">${escapeHtml(item)}</div>`)
          .join("")}`
      : ""
  }

  <div class="footer">Generated by Only4PDF - only4pdf.com</div>
</body>
</html>`;
}

export async function exportSummaryAsPdf(summary: SummaryExportInput): Promise<Buffer> {
  const html = buildSummaryHtml(summary);
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "load" });
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "12mm", right: "12mm", bottom: "12mm", left: "12mm" },
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

export async function exportSummary(
  summary: SummaryExportInput,
  format: SummaryExportFormat
): Promise<{ buffer: Buffer; mimeType: string }> {
  if (format === "txt") {
    return {
      buffer: Buffer.from(buildPlainText(summary), "utf8"),
      mimeType: "text/plain;charset=utf-8",
    };
  }

  if (format === "docx") {
    return {
      buffer: await exportSummaryAsDocx(summary),
      mimeType:
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    };
  }

  return {
    buffer: await exportSummaryAsPdf(summary),
    mimeType: "application/pdf",
  };
}
